services:
  evolution-api:
    image: evoapicloud/evolution-api:v2.3.6
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=oANX0yXAWM1QGxRhkkwf
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution:evolution@evolution-api-db:5432/evolution
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evolution-redis:6379
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1037024466
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS
      - LOG_COLOR=true
    depends_on:
      evolution-api-db:
        condition: service_healthy
      evolution-redis:
        condition: service_healthy
    volumes:
      - evolution_api_data:/evolution/instances

  evolution-api-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=evolution
      - POSTGRES_PASSWORD=evolution
      - POSTGRES_DB=evolution
    volumes:
      - evolution_api_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evolution"]
      interval: 5s
      timeout: 5s
      retries: 5

  evolution-redis:
    image: redis:7-alpine
    volumes:
      - evolution_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  evolution_api_data:
  evolution_api_db_data:
  evolution_redis_data:
